### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stoggi** [jorgen/yat#18]
I like your project, and want to make some contributions. But you haven't specified a license. Which means it is protected under your copyright and is difficult to use in other open source projects.

If you do want to make this open source, check out http://choosealicense.com/ to select one that suits you. I highly recommend adding one so that other people know what your intentions with your code are.

Adding a license can be as simple as adding a file to your repository called `LICENSE` containing the text of your chosen license.

**Comment by stoggi** [comment]
Hm, sorry I didn't realise you have the MIT license comment at the top of many of your source files.

**Comment by jorgen** [comment]
Yeah, all files are suppose to be MIT licensed.
